config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  resources :github_payloads, only: [:create]
  resource :session, only: [:new, :create, :destroy]

  get "/auth/:provider/callback", to: "sessions#create"
  get "/auth/githubteammember", as: "githubteammember_auth"
  root to: "pull_requests#index"

  resources :pull_requests, only: :index
end

app/models/channel.rb
class Channel < ActiveRecord::Base
  validates :name, presence: true
  validates :name, uniqueness: { scope: :webhook_url }
  validates :webhook_url, presence: true

  has_many :projects, as: :default_channel, dependent: :destroy
  has_many :tags, dependent: :destroy
  has_many :active_pull_requests,
    -> { active },
    through: :tags,
    source: :pull_requests

  def self.with_tag_name(tag_names)
    joins(:tags).find_by(tags: { name: tag_names })
  end
end

app/models/null_pull_request.rb
class NullPullRequest
  def update(*args)
    # noop
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  validates :default_channel, presence: true
  validates :github_url, presence: true, uniqueness: true
  validates :name, presence: true, uniqueness: true

  belongs_to :default_channel, class_name: "Channel"
end

app/models/pull_request.rb
class PullRequest < ActiveRecord::Base
  REPOST_THRESHOLD = ENV.fetch("REPOST_THRESHOLD").to_i

  validates :github_url, presence: true, uniqueness: true
  validates :repo_name, presence: true
  validates :repo_github_url, presence: true
  validates :status, presence: true, inclusion: { in: ["needs review", "in progress", "completed"] }
  validates :title, presence: true
  validates :user_name, presence: true
  validates :user_github_url, presence: true
  validates :avatar_url, presence: true

  has_and_belongs_to_many :tags
  has_many :channels, through: :tags

  time_for_a_boolean :reposted

  def self.active
    where(status: ["needs review", "in progress"])
  end

  def self.for_tags(tag_names)
    if tag_names.present?
      joins(:tags).where(tags: { name: tag_names })
    else
      all
    end
  end

  def self.needs_reposting
    timestamp = REPOST_THRESHOLD.minutes.ago

    updated_before(timestamp).
      where(status: "needs review", reposted_at: nil)
  end

  def self.updated_before(timestamp)
    where("updated_at <= ?", timestamp)
  end

  def tag_names
    tags.map(&:name)
  end

  def number
    github_url.split("/").last
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  validates :channel, presence: true
  validates :channel_id, presence: true
  validates :name, presence: true
  validates :name, uniqueness: true

  before_validation :normalize_name

  belongs_to :channel

  has_and_belongs_to_many :pull_requests

  def self.with_active_pull_requests
    joins(:pull_requests).
      merge(PullRequest.active).
      distinct
  end

  def pull_requests_count
    pull_requests.active.count
  end

  private

  def normalize_name
    if name.present?
      self.name = name.downcase
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
  before_action :ensure_team_member
  force_ssl if: :ssl_configured?


  private

  def ensure_team_member
    unless github_username || Rails.env.test?
      redirect_to new_session_path
    end
  end

  def github_username
    session[:github_username]
  end

  def ssl_configured?
    !Rails.env.development? && !Rails.env.test?
  end
end

app/controllers/github_payloads_controller.rb
class GithubPayloadsController < ApplicationController
  before_action VerifyGithubSignature.new(ENV["GITHUB_SECRET_KEY"])
  skip_before_action :ensure_team_member

  def create
    action_matching(parser, pull_request).call

    head :ok
  end

  private

  def action_matching(*args)
    actions
      .find { |action| action.matches(*args) }
      .new(*args)
  end

  def actions
    [
      CreateNewPr,
      CompletePr,
      CompleteClosedPr,
      MarkPrNeedsReview,
      MarkPrInProgress,
      NoMatchingAction,
    ]
  end

  def parser
    @_parser ||= PayloadParser.new(payload_params, request.headers)
  end

  def payload_params
    params[:github_payload].permit!
  end

  def pr_params
    parser.params
  end

  def pull_request
    PullRequest.find_by(github_url: parser.github_url) || NullPullRequest.new
  end
end

app/controllers/pull_requests_controller.rb
class PullRequestsController < ApplicationController
  helper_method :grouped_pull_requests, :tags, :tags_to_filter_by
  skip_before_action :ensure_team_member, only: :index

  def index
    respond_to do |format|
      format.html { ensure_team_member }
      format.json { render json: pull_requests }
    end
  end

  private

  def grouped_pull_requests
    pull_requests.group_by(&:status)
  end

  def pull_requests
    @pull_requests ||= PullRequest.
      for_tags(tags_to_filter_by).
      active.
      distinct
  end

  def tags
    @tags ||= Tag.with_active_pull_requests
  end

  def tags_to_filter_by
    params.fetch(:tags, "").split(",")
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :ensure_team_member

  def new

  end

  def create
    if auth_hash.credentials.team_member?
      session[:github_username] = github_username
      redirect_to root_path
    else
      flash[:error] = "You cannot access this site" \
                      "unless you are a member of the team"
      redirect_to root_path
    end
  end

  def destroy
    reset_session
    redirect_to root_path
  end

  protected

  def auth_hash
    request.env["omniauth.auth"]
  end

  def github_username
    auth_hash["info"]["nickname"]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def embedded_svg(filename, options = {})
    assets = Rails.application.assets
    file = assets.find_asset(filename)
    render file: file.pathname
  end

  def all_tags_channels
    Tag.joins(:channel).order(:name).pluck("tags.name", "channels.name")
  end
end

app/helpers/tags_helper.rb
module TagsHelper
  def toggle_tag_on_path(tag)
    if active_tag?(tag)
      remove_tag_from_path(tag)
    else
      add_tag_to_path(tag)
    end
  end

  def tag_classes(tag)
    classes = ["tag-toggle", tag]

    if active_tag?(tag)
      classes << "is-active"
    end

    classes
  end

  def add_tag_to_path(tag)
    current_tags = tags_to_filter_by + [tag]
    { tags: current_tags.join(",") }
  end

  def remove_tag_from_path(tag)
    current_tags = tags_to_filter_by - [tag]
    { tags: current_tags.join(",") }
  end

  def active_tag?(tag)
    tags_to_filter_by.include?(tag)
  end
end

app/views/application/_analytics.html.erb
<% if ENV["SEGMENT_IO_KEY"] %>
  <script type="text/javascript">
    window.analytics=window.analytics||[],window.analytics.methods=["identify","group","track","page","pageview","alias","ready","on","once","off","trackLink","trackForm","trackClick","trackSubmit"],window.analytics.factory=function(t){return function(){var a=Array.prototype.slice.call(arguments);return a.unshift(t),window.analytics.push(a),window.analytics}};for(var i=0;i<window.analytics.methods.length;i++){var key=window.analytics.methods[i];window.analytics[key]=window.analytics.factory(key)}window.analytics.load=function(t){if(!document.getElementById("analytics-js")){var a=document.createElement("script");a.type="text/javascript",a.id="analytics-js",a.async=!0,a.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.io/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(a,n)}},window.analytics.SNIPPET_VERSION="2.0.9",
    window.analytics.load("<%= ENV["SEGMENT_IO_KEY"] %>");
    window.analytics.page();
  </script>
<% end %>

app/views/application/_flashes.html.erb
<% if flash.any? %>
  <div id="flash">
    <% flash.each do |key, value| -%>
      <div id="flash_<%= key %>"><%= value %></div>
    <% end -%>
  </div>
<% end %>

app/views/application/_javascript.html.erb
<%= javascript_include_tag :application %>

<%= yield :javascript %>

<%= render "analytics" %>

<% if Rails.env.test? %>
  <%= javascript_tag do %>
    $.fx.off = true;
    $.ajaxSetup({ async: false });
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="ROBOTS" content="NOODP" />
  <meta name="viewport" content="initial-scale=1" />
  <title><%= title %></title>
  <script src="//use.typekit.net/jax3oxe.js"></script>
  <script>try{Typekit.load();}catch(e){}</script>
  <%= stylesheet_link_tag :application, media: "all" %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag "favicon.ico" %>
</head>
<body>
  <%= render "flashes" -%>
  <%= yield %>
  <%= render "javascript" %>
</body>
</html>

app/views/pages/setup.html.erb
<div class="page-header">
  <div class="container">
    <h1 class="page-header-logo">
      <%= link_to "Pester", root_url %>
    </h1>
    <%= link_to root_url, class: "page-header-nav-link" do %>
      Back to Home &rarr;
    <% end %>
  </div>
</div>

<div class="slice">
  <div class="container">
    <p>Getting Started</p>
  </div>
</div>

<div class="container">
  <div class="content">
    <section>
      <h2>What is Pester?</h2>
      <p>Pester is a tool to help get your pull requests reviewed. Once
      configured, pull requests with a matching <code>#tag</code> will be added
      to the Pester UI and the appropriate Slack channel.</p>
      <p>New PRs have a "Needs Review" status. Once there are one or more
      comments, it will be moved to to "In Progress".</p>
      <p>Any comment containing <code>LGTM</code> will consider the PR
      closed.</p>
      <p>Any comment containing <code>NRR</code> (needs re-review) will kick
      it back to "Needs Review".</p>
    </section>

    <section>
      <h2>Setup: Tags and Channels</h2>
      <p>Configure tags and channels in the <%= link_to "Admin Panel", admin_root_path %>.</p>
      <p>The currently-enabled tags and their associated channels are:</p>
      <table>
        <tr>
          <th>Tag</th>
          <th>Slack Channel</th>
        </tr>
        <% all_tags_channels.each do |tag, channel| %>
          <tr>
            <td>#<%= tag %></td>
            <td><%= channel %></td>
          </tr>
        <% end %>
      </table>
    </section>

    <section>
      <h2>Setup: Add the Webhook to your GitHub repo</h2>
      <ol>
        <li>Visit <code>https://github.com/$ORGANIZATION/$REPO/settings/hooks/new</code>.</li>
        <li>Enter <code><%= ENV["WEBHOOK_URL"] %></code> for the Payload URL.</li>
        <li>Enter <code><%= ENV["GITHUB_SECRET_KEY"] %></code> for the secret.</li>
        <li>Select <code>Send me everything</code>, and submit.</li>
        <li>
          <p>Submit a PR! When given a matching <code>#tag</code> in the
          description, it will be posted to both the Pester UI and its
          associated Slack channel.</p>
        </li>
      </ol>
    </section>

    <section>
      <h2>Contributing</h2>
      <ul>
        <li>
          Check out the repo on <a href="https://github.com/thoughtbot/pester">GitHub</a>.
        </li>
      </ul>
    </section>
  </div>
</div>

app/views/pull_requests/_pull_request.html.erb
<li class="table-list-item">
  <div class="table-list-cell">
    <img
       src="<%= pull_request.avatar_url %>"
       alt="<%= pull_request.user_name %>"
       class="avatar"
    >
  </div>

  <div class="table-list-cell stacked">
    <%= link_to pull_request.title, pull_request.github_url, class: "table-list-cell-title" %>
    <span class="table-list-cell-subtitle">
      #<%= pull_request.number %>
      opened <%= time_ago_in_words pull_request.created_at %> ago by
      <%= link_to pull_request.user_name, pull_request.user_github_url %>
      in
      <%= link_to pull_request.repo_name, pull_request.repo_github_url %>
    </span>
  </div>

  <div class="table-list-cell hide-mobile">
    <% pull_request.tags.each do |tag| %>
      <span class="tag <%= tag.name %>" data-role="tag"><%= tag.name %></span>
    <% end %>
  </div>

  <div class="table-list-cell hide-mobile">
    <div class="comment-count">
      <%= embedded_svg "svg/comment.svg" %>
      <span data-role="comment-count"><%= pull_request.comment_count %></span>
    </div>
  </div>
</li>

app/views/pull_requests/index.html.erb
<header class="page-header">
  <div class="container">
    <h1 class="page-header-logo">
      <%= link_to "Pester", root_url %>
    </h1>
    <nav class="page-header-nav">
      <ul>
        <li class="page-header-nav-item">
          <%= link_to "Getting Started?", page_path("setup"), class: "page-header-nav-link" %>
        </li>
        <li class="page-header-nav-item">
          <%= link_to "Admin", admin_root_path, class: "page-header-nav-link" %>
        </li>
        <li class="page-header-nav-item">
          <%= link_to "Sign Out", session_path, method: :delete, class: "page-header-nav-link" %>
        </li>
      </ul>
    </nav>
  </div>
</header>

<section class="slice">
  <div class="container">
    <ol class="tags">
      <li>
        <span class="slice-title">
          Filter:
        </span>
      </li>
      <%= render tags %>
    </ol>
  </div>
</section>

<main>
  <div class="container">
    <% if grouped_pull_requests["needs review"].present? %>
      <ol class="table-list">
        <li class="table-list-item">
          <div class="table-list-cell stacked">
            <h3>Needs Review</h3>
            <span class="table-list-cell-subtitle">Pull Requests waiting for feedback</span>
          </div>
        </li>
        <%= render grouped_pull_requests["needs review"] %>
      </ol>
    <% end %>

    <% if grouped_pull_requests["in progress"].present? %>
      <ol class="table-list">
        <li class="table-list-item">
          <div class="table-list-cell stacked">
            <h3>In Progress</h3>
            <span class="table-list-cell-subtitle">Pull Requests with some feedback</span>
          </div>
        </li>
        <%= render grouped_pull_requests["in progress"] %>
      </ol>
    <% end %>
  </div>
</main>

app/views/tags/_tag.html.erb
<li>
  <%= link_to(toggle_tag_on_path(tag.name), class: tag_classes(tag.name)) do %>
    <%= tag.name %>
    <span class="tag-badge" data-role="pr-count"><%= tag.pull_requests_count %></span>
  <% end %>
</li>